# Generated by Django 5.1.5 on 2025-02-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
