# Generated by Django 5.1.5 on 2025-02-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficesystem', '0004_appointmentslot_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medical_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalofficesystem.medicaloffice'),
        ),
    ]
