# Generated by Django 5.1.5 on 2025-02-18 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalofficesystem', '0005_doctor_medical_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicalofficesystem.appointment'),
        ),
    ]
